### ISSUE TITLE
Can based on  DirectFB  library?

### ISSUE THREAD

**Issue by boslad** [caveadventure/tiletel#1]
The  tiletel  is very nice, and it  comes in three versions: one that uses the SDL2 library, one that uses the Qt library, and as a web server that serves images to a web-browser client.
But  i  like DirectFB library  very much, and  using  many  tools based on libdirectfb. So  can tiletel  be based on DirecFB? And  how?

**Comment by caveadventure** [comment]
Sure, why not, tiltel can be ported to any library that can display pixels. What is your use case for DirectFB? DirectFB seems to be rarely used on the Linux desktop, I know little about it.

**Comment by boslad** [comment]
I am very glad to hear this! Yes  DirectFB is rarely used on the Linux desktop, it is mostly used on Embedded system. I like DFBTerm that is based on DirectFB+LiTE. Unluckily, DFBTerm  doesn't support UTF-8(CJK) character set display. On the contrary, the tiltel can do it. I eagerly want you to port it to DirectFB+LiTE. I hope that DFBTerm can display CJK character set  by using libtsm. Can you help me?

**Comment by ivan-tkatchev** [comment]
http://directfb.org has been down for many days and I couldn't find any API documentation anywhere. Is DirectFB abandoned?

**Comment by boslad** [comment]
Maybe  you can find it here. http://git.pld-linux.org/

**Comment by boslad** [comment]
In my option, DFBTerm is referenced which is based on DirectFB and LiTE.

**Comment by ivan-tkatchev** [comment]
Seems like DFBTerm sources were also hosted on directfb.org and have now disappeared from the Internet. (pld-linux.org only hosts package description files, they reference sources from directfb.org)

**Comment by boslad** [comment]
You may click the link http://git.pld-linux.org/?p=packages/DFBTerm.git;a=snapshot;h=6e2462492994198b3166e1eaf520545e5be322c4;sf=tgz

**Comment by boslad** [comment]
DirectFB-1.7.6-5    http://git.pld-linux.org/?p=packages/DirectFB.git;a=snapshot;h=c6eb9f384b712dd27d79e1404f409c3f36f3ffa7;sf=tgz
LiTE-0.8.10  https://github.com/eslinux/DirectFB-ilixi-LiTE

**Comment by caveadventure** [comment]
These are .spec files for building RPM packages, not sources.

**Comment by boslad** [comment]
I'm sorry. Would  you mind to tell   me your E-mail?  I  can  send the resources  to you   by it .

**Comment by caveadventure** [comment]
tkatchev gmail.com

**Comment by boslad** [comment]
Another E-mail? I can not visit  gmail?

**Comment by caveadventure** [comment]
It's OK, I think I figured this out myself, there are DirectFB sources on Github.

**Comment by caveadventure** [comment]
I've added DirectFB support. You can try it if you compile with

    mkdir build
    cd build
    cmake -DTOOLKIT=dfb
    make

Can you check that it works on your machine?

**Comment by boslad** [comment]
Thanks a lot. I will try it very soon.

**Comment by boslad** [comment]
@caveadventure  When i use it as a  terminal emulator, i type a english letter, such as "e",  double letter  "ee" occurs. Why?

**Comment by caveadventure** [comment]
What distribution and architecture is your computer running? What "system=" parameter is configured for your DirectFB? Are you using any special keyboard layouts or input methods?

**Comment by boslad** [comment]
@caveadventure I use Slax 7.0.8, which is based on slackware, and the architecture is x86. The "system= " is configured  fbdev in  file .directfbrc.

**Comment by ivan-tkatchev** [comment]
I can't reproduce this in my machine.

Please try the solution proposed here:
https://bbs.archlinux.org/viewtopic.php?pid=699993#p699993

**Comment by boslad** [comment]
@ivan-tkatchev  Thank you very much. The problem is fixed  by adding a line "disable-module=linux_input" in file directfbrc.
